
dbconf:
  user: "local"
  pass: "local"
  dbname: "local"
  port: 5432
  host: "localhost"

logfile: logs

xmlfiledestination: ./certconfig.xml

  #- cdn.t.supplyframe.com

 # "sentry.tindie.com":
 #   - "54.203.191.248"

dns:
  - "datasheetarchive.com"
  - "bom.api.supplyframe.com"
  - "www.hackaday.io"
  - "hackadayarchive.com"
  - "w.supplyframe.com"
  - "gopart.com"
  - "ti.enterprise-demo.supplyframe.com"
  - "fe.enterprise-demo.supplyframe.com"
  - "digikey.enterprise-demo.supplyframe.com"
  - "qa.pages.findchips.com"
  - "pages.findchips.com"
  - "qa.oemstrade.com"
  - "qa.rest.hackaday.io"
  - "adtool.supplyframe.com"
  - "t.supplyframe.com"
  - "qa.t.supplyframe.com"

currentDomains:
  - "datasheetarchive.com":
    - "alpha.datasheetarchive.com"
    - "origin-cdn2.datasheetarchive.com"
    - "www.datasheetarchive.com"
  - "bom.api.supplyframe.com":
  - "hackaday.io":
    - "www.hackaday.io"
    - "freeze.hackaday.io"
    - "journal.hackaday.io"
    - "space.hackaday.io"
  - "hackaday.io": 
    - "static.hackaday.io" 
    - "qa.hackaday.io"
    - "analytics.hackaday.io"
    - "cdn.hackaday.io"
    - "origin-cdn.hackaday.io"
    - "cdn.qa.hackaday.io"
    - "auth.hackaday.io"
    - "api.hackaday.io"
    - "dev.hackaday.io" 
    - "hackaday.com" 
    - "www.hackaday.com"
  - "hackadayarchive.com":
  - "*.supplyframe.com": # This is in digicert; but w.supplyframe.com is in let's encrypt
  - "gopart.com":
    - "www.gopart.com"
  - "pages.findchips.com":
  - 
