
dbconf:
  user: "local"
  pass: "local"
  dbname: "local"
  port: 5432
  host: "localhost"

logfile: logs

xmlfiledestination: ./certconfig.xml

  #- t.supplyframe.com, cdn.t.supplyframe.com

 # "sentry.tindie.com":
 #   - "54.203.191.248"

dns:
  - "datasheetarchive.com"
  - "bom.api.supplyframe.com"
  - "www.hackaday.io"
  - "hackadayarchive.com"
  - "w.supplyframe.com"
  - "gopart.com"
  - "ti.enterprise-demo.supplyframe.com"
  - "fe.enterprise-demo.supplyframe.com"
  - "digikey.enterprise-demo.supplyframe.com"
  - "qa.pages.findchips.com"
  - "pages.findchips.com"
  - "qa.oemstrade.com"
  - "qa.rest.hackaday.io"
  - "adtool.supplyframe.com"
  - "t.supplyframe.com"
  - "qa.t.supplyframe.com"
